version: "3.3"
services:
  web:
    build: ./app
    image: 014831715366.dkr.ecr.us-east-1.amazonaws.com/workshop222:workshop2.0_web
    command: gunicorn nc_tutorials.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_NAME=nucampnctutorials
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=nucampnctutorials.cie8luhyrqec.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST= ec2-52-91-160-140.compute-1.amazonaws.com 
      
  nginx:
    build: ./nginx
    image: 014831715366.dkr.ecr.us-east-1.amazonaws.com/workshop222:workshop2.0_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume:
